
package org.val.win;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-03T16:36:03.127+02:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://contract.service.win.val.org/")
public class NotFoundException_Exception extends Exception {

    private org.val.win.NotFoundException notFoundException;

    public NotFoundException_Exception() {
        super();
    }

    public NotFoundException_Exception(String message) {
        super(message);
    }

    public NotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NotFoundException_Exception(String message, org.val.win.NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public NotFoundException_Exception(String message, org.val.win.NotFoundException notFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public org.val.win.NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
