
package org.val.win;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-03T16:36:03.071+02:00
 * Generated source version: 3.2.6
 *
 */
public final class P7Service_P7ServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.win.val.org/", "P7ServiceImplService");

    private P7Service_P7ServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = P7ServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        P7ServiceImplService ss = new P7ServiceImplService(wsdlURL, SERVICE_NAME);
        P7Service port = ss.getP7ServiceImplPort();

        {
        System.out.println("Invoking retardEmprunt...");
        org.val.win.Emprunt _retardEmprunt_arg0 = null;
        port.retardEmprunt(_retardEmprunt_arg0);


        }
        {
        System.out.println("Invoking getListDispo...");
        org.val.win.AnyTypeArray _getListDispo__return = port.getListDispo();
        System.out.println("getListDispo.result=" + _getListDispo__return);


        }
        {
        System.out.println("Invoking getListEmprunt...");
        org.val.win.AnyTypeArray _getListEmprunt__return = port.getListEmprunt();
        System.out.println("getListEmprunt.result=" + _getListEmprunt__return);


        }
        {
        System.out.println("Invoking utilisateurLogin...");
        java.lang.String _utilisateurLogin_arg0 = "";
        java.lang.String _utilisateurLogin_arg1 = "";
        org.val.win.Utilisateur _utilisateurLogin__return = port.utilisateurLogin(_utilisateurLogin_arg0, _utilisateurLogin_arg1);
        System.out.println("utilisateurLogin.result=" + _utilisateurLogin__return);


        }
        {
        System.out.println("Invoking emprunt...");
        org.val.win.Emprunt _emprunt_arg0 = null;
        org.val.win.Utilisateur _emprunt_arg1 = null;
        org.val.win.Ouvrage _emprunt_arg2 = null;
        try {
            port.emprunt(_emprunt_arg0, _emprunt_arg1, _emprunt_arg2);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getListEmpruntUtilisateur...");
        org.val.win.Utilisateur _getListEmpruntUtilisateur_arg0 = null;
        org.val.win.AnyTypeArray _getListEmpruntUtilisateur__return = port.getListEmpruntUtilisateur(_getListEmpruntUtilisateur_arg0);
        System.out.println("getListEmpruntUtilisateur.result=" + _getListEmpruntUtilisateur__return);


        }
        {
        System.out.println("Invoking getListOuvrage...");
        org.val.win.OuvrageArray _getListOuvrage__return = port.getListOuvrage();
        System.out.println("getListOuvrage.result=" + _getListOuvrage__return);


        }
        {
        System.out.println("Invoking prolongationEmprunt...");
        org.val.win.Emprunt _prolongationEmprunt_arg0 = null;
        port.prolongationEmprunt(_prolongationEmprunt_arg0);


        }
        {
        System.out.println("Invoking fermerEmprunt...");
        org.val.win.Emprunt _fermerEmprunt_arg0 = null;
        try {
            port.fermerEmprunt(_fermerEmprunt_arg0);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
